class Language_Names:
    '''
    Replace the un-formatted name that is generated by Local Time Tracker with something more pretty and accurate.
    **DONT** use emojies, matplotlib doesn't like them. There are workaround's, but there 'hacky' and require you to change defualt font path.

    'python':'snek lang'
    will replace every occurence of 'python' to 'snek lang'.
    '''
    def __init__(self):
        self.Names: dict = {
            'python': 'Python',
            'javascript': 'JavaScript',
            'typescript': 'TypeScript',
            'csharp': 'C#',
            'c': 'C',
            'r': 'R',
            'go': 'GO',
            'ruby': 'Ruby',
            'swift': 'Swift',
            'kotlin': 'Kotlin',
            'haskell': 'Haskell',
            'cpp': 'C++',
            'java': 'Java',
            'markdown': '.md',
            'txt':'.txt',
            'Log':'.log',
            'json':'.json',
            'jsonc':'.jsonc',
            'yaml':'.yaml',
            'gitignore':'.gitignore'
        }
        self.Programming_Names: list = [
            'python',
            'javascript',
            'typescript',
            'csharp',
            'cpp',
            'c',
            'r',
            'go',
            'ruby',
            'swift',
            'kotlin',
            'haskell',
            'cpp',
            'java'
        ]